#!/bin/bash
URL="http://ip-api.com/json/"
ip="157.47.48.49"
val=$(curl $(echo $URL$ip) | jq --jsonargs '.country, .regionName, .city, .lat, .lon, .isp' | tr '\n' '-')
echo $val
lat=$(echo $val | awk -F "-" '{ print $4}')
long=$(echo $val | awk -F "-" '{ print $5}')
map_link=$(echo "https://maps.google.com/?q=$lat,$long")
echo $map_link
